version: "3.9"

services: 

    baylor-api: 
        build: ./backend
        ports: 
            - "4000:4000"
        volumes: 
            - app-data:/usr/src/app/build/media
        networks:
            - node-app
        depends_on:
            - postgresql

    baylor-frontend: 
        build: ./frontend
        ports: 
            - "3000:3000"
        networks:
            - node-app
        depends_on:
            - baylor-api

    chronium-browserless: 
        image: browserless/chrome
        ports: 
            - "6000:3000"
        networks:
            - node-app

    postgresql:
        image: postgres
        environment:
            - POSTGRES_DB=baylor_company
            - POSTGRES_USER=bayloradmin
            - POSTGRES_PASSWORD=b4yl0rtr4d1ng
        ports: 
            - "6543:5432"
        volumes: 
            - postgres-data:/var/lib/postgresql/data
        networks:
            - node-app

networks: 
    node-app: 
        driver: bridge

volumes: 
    postgres-data:
        driver: local
    app-data:
        driver: local
